/* eslint-disable prefer-const */
import {
  Token,
  Bundle,
} from './../types/schema'
import { BigDecimal, ethereum } from '@graphprotocol/graph-ts'
import assert from 'assert'

// This class should be autogenerated from the schema
export class TokenData {
  static add(timestamp: i32, token: Token,
    tokenPrice: BigDecimal, volume: BigDecimal,
    volumeUSD: BigDecimal, feesUSD: BigDecimal) {
    assert(false, "not implemented")
  }
}

export function updateTokenData(token: Token, event: ethereum.Event, volume: BigDecimal, volumeUSD: BigDecimal, feesUSD: BigDecimal) {
  let bundle = Bundle.load('1')
  let timestamp = event.block.timestamp.toI32()
  let tokenPrice = token.derivedETH.times(bundle.ethPriceUSD)

  TokenData.add(timestamp, token, tokenPrice, volume, volumeUSD, feesUSD)
}
